[pytest]
filterwarnings =
    ignore:.*Eventlet is deprecated.*
    ignore::Warning:engineio.async_drivers.eventlet
    ignore:.*datetime.datetime.utcnow\(\) is deprecated.*:DeprecationWarning
    ignore:.*Setting the shape on a NumPy array has been deprecated in NumPy 2.5.*:DeprecationWarning

